### ISSUE TITLE
issues using cuda

### ISSUE THREAD

**Issue by solidstudio** [yuwenmichael/Grounding-DINO-Batch-Inference#3]
Hi does this work with cuda? I'm using:

https://github.com/HumanSignal/label-studio-ml-backend/tree/master/label_studio_ml/examples/grounding_dino

and getting the following:

`label-studio-ml-backend  | /app/Grounding-DINO-Batch-Inference/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
label-studio-ml-backend  |   warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")`

and

` output = _C.ms_deform_attn_forward(\\nNameError: name \'_C\' is not defined`

**Comment by yuwenmichael** [comment]
Yes, it should work on cuda. Please refers [here](https://github.com/yuwenmichael/Grounding-DINO-Batch-Inference/blob/7d8b78b431e88c34e4b55225147bec99e7442f57/inference_gdino.py#L27) by modifying cpu to cuda.
